/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function Button({ children, className, variant = 'primary' }) {
  const baseClasses = "justify-center px-8 py-4 max-w-full text-3xl rounded-3xl w-[265px]";
  const variantClasses = {
    primary: "text-white bg-sky-600",
    outline: "text-sky-600 bg-white border border-sky-600 border-solid"
  };

  return (
    <button className={`${baseClasses} ${variantClasses[variant]} ${className}`}>
      {children}
    </button>
  );
}

export default Button;