/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function Pagination({ totalPages, currentPage, className }) {
  return (
    <div className={`flex gap-2.5 ${className}`}>
      {[...Array(totalPages)].map((_, index) => (
        <div
          key={index}
          className={`shrink-0 rounded-full h-[13px] w-[13px] ${
            index + 1 === currentPage ? 'bg-blue-950' : 'bg-zinc-300'
          }`}
        />
      ))}
    </div>
  );
}

export default Pagination;