/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import Button from './Button';
import ImageGallery from './ImageGallery';
import Pagination from './Pagination';

function SignInPage() {
  return (
    <main className="flex flex-col items-center px-4 py-9 mx-auto w-full bg-white max-w-[480px]">
      <header className="justify-center self-stretch px-8 py-14 text-4xl rounded-full bg-stone-200 bg-opacity-40 text-sky-600 text-opacity-90">
        Sign In And Get Started With Book It...
      </header>
      <Button className="mt-14" variant="primary">
        Find a flight
      </Button>
      <Button className="mt-14" variant="primary">
        Sign in
      </Button>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/25bdd136c6432c215c3bf7b96eda8dcbca00c9bae1c5f400a70067c4a66b0452?apiKey=661e1fa212c74d1c94d19e320025bbf6&"
        alt=""
        className="mt-10 w-64 max-w-full border border-solid aspect-[50] border-black border-opacity-20 stroke-[1px] stroke-black stroke-opacity-20"
      />
      <ImageGallery />
      <Button className="mt-6 ml-4" variant="outline">
        Create your account
      </Button>
      <Pagination className="mt-24" totalPages={3} currentPage={3} />
    </main>
  );
}

export default SignInPage;