/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import ReviewCard from './ReviewCard';

const CustomerReviews = () => {
  const reviews = [
    {
      name: "Favour Simeon",
      location: "Lagos, Nigeria.",
      review: "i love your perfumes so much."
    },
    {
      name: "Comfort Austin",
      location: "Enugu, Nigeria.",
      review: "Amazing fragance.."
    }
  ];

  return (
    <section className="mt-16 max-md:mt-10 max-md:max-w-full">
      <h2 className="justify-center self-center px-8 py-11 mt-16 ml-6 text-5xl font-bold rounded-xl border-solid shadow-sm border-[3px] border-stone-700 text-neutral-400 max-md:px-5 max-md:mt-10 max-md:max-w-full max-md:text-4xl">
        CUSTOMER'S REVIEWS
      </h2>
      <div className="flex gap-5 mt-16 max-md:flex-col max-md:gap-0 max-md:mt-10">
        {reviews.map((review, index) => (
          <ReviewCard key={index} {...review} />
        ))}
      </div>
    </section>
  );
};

export default CustomerReviews;