/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import ProductCard from './ProductCard';

const FeaturedProducts = () => {
  const products = [
    { name: "Choco Musk", price: "88,000.00" },
    { name: "Castle Princess", price: "50,000.00" },
    { name: "Rayhaan", price: "100,000.00" }
  ];

  return (
    <section className="flex flex-col pr-10 pl-20 mt-14 w-full max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <h2 className="text-4xl font-bold text-neutral-400 max-md:max-w-full">FEATURED PRODUCTS</h2>
      <div className="shrink-0 mt-2.5 max-w-full border-solid bg-stone-500 border-[3px] border-stone-500 h-[5px] w-[1223px]" />
      <div className="flex gap-5 self-center mt-3.5 w-full text-2xl max-w-[1085px] max-md:flex-wrap max-md:max-w-full">
        <div className="flex-auto my-auto text-black">Showing 1-3 of 6 results</div>
        <button className="justify-center px-1.5 py-4 text-white bg-teal-900 rounded-xl">SEE MORE</button>
      </div>
      <div className="self-center mt-11 w-full max-w-[1135px] max-md:mt-10 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col max-md:gap-0">
          <div className="flex flex-col w-[70%] max-md:ml-0 max-md:w-full">
            <div className="grow max-md:mt-10 max-md:max-w-full">
              <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
                  <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/a5a2a2530c72d06e6c5d581cf8a0f9fb76ffd2e56e783a49ced854e47ec3243a?apiKey=661e1fa212c74d1c94d19e320025bbf6&" alt="Featured product 1" className="w-full aspect-square max-md:mt-10" />
                </div>
                <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
                  <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/867fbf38d9a2df8ac75068c51e72d5b26dcb1d952f2ea19a420be60dc177c605?apiKey=661e1fa212c74d1c94d19e320025bbf6&" alt="Featured product 2" className="w-full aspect-square max-md:mt-10" />
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-col ml-5 w-[30%] max-md:ml-0 max-md:w-full">
            <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/c6456958cba058f4c536762fbdc8b61fff9c53575bff517a698b24565030f3ae?apiKey=661e1fa212c74d1c94d19e320025bbf6&" alt="Featured product 3" className="grow w-full aspect-[0.94] max-md:mt-10" />
          </div>
        </div>
      </div>
      <div className="self-center mt-10 w-full max-w-[1050px] max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col max-md:gap-0">
          {products.map((product, index) => (
            <ProductCard key={index} name={product.name} price={product.price} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default FeaturedProducts;