/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Footer = () => {
  return (
    <footer className="flex flex-col flex-wrap content-center px-7 py-9 mt-32 text-4xl font-bold text-white bg-stone-500 max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div className="max-md:max-w-full">My Account</div>
      <div className="flex gap-5 justify-between mt-4 max-md:flex-wrap max-md:pr-5 max-md:max-w-full">
        <nav className="flex flex-col my-auto whitespace-nowrap">
          <h2 className="text-6xl max-md:text-4xl">Shop</h2>
          <ul>
            <li className="mt-12 max-md:mt-10">Products</li>
            <li className="mt-9">Checkout</li>
          </ul>
        </nav>
        <div className="flex flex-col max-md:max-w-full">
          <div className="flex flex-col px-14 max-md:px-5 max-md:max-w-full">
            <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/81db8bac062de8744c4950c849b5f1000bc294f156857dad7d5ee4b660691995?apiKey=661e1fa212c74d1c94d19e320025bbf6&" alt="Company logo" className="max-w-full aspect-[1.02] w-[125px]" />
            <address className="mt-7 not-italic">
              <p>+234 093 923 3914</p>
              <p className="mt-9 max-md:max-w-full">favyscentss@gmsil.com</p>
              <p className="self-center mt-7">Lagos, Nigeria.</p>
            </address>
          </div>
        </div>
      </div>
      <div className="mt-7 max-md:max-w-full">Privacy Policy</div>
    </footer>
  );
};

export default Footer;