/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Hero = () => {
  return (
    <section className="flex flex-col px-11 pt-10 pb-6 mt-32 w-full rounded-xl bg-stone-500 max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div className="flex overflow-hidden relative z-10 flex-col items-start py-16 pr-20 pl-6 font-bold min-h-[279px] max-md:px-5 max-md:max-w-full">
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/7f83f05775f357654ac8cb4aa08b6ade0e7da17b77a353af7d6fb7d9dc1b2bda?apiKey=661e1fa212c74d1c94d19e320025bbf6&" alt="Background image" className="object-cover absolute inset-0 size-full" />
        <h1 className="relative ml-14 text-4xl text-neutral-100 max-md:ml-2.5">
          WELCOME TO
        </h1>
        <h2 className="relative mt-11 text-8xl text-white max-md:mt-10 max-md:max-w-full max-md:text-4xl">
          FAVYSCENTS
        </h2>
      </div>
      <div className="mt-0 ml-20 max-w-full w-[788px]">
        <div className="flex gap-5 max-md:flex-col max-md:gap-0">
          <div className="flex flex-col w-[78%] max-md:ml-0 max-md:w-full">
            <p className="mt-32 text-4xl italic font-light text-white max-md:mt-10 max-md:max-w-full">
              Experience the Art of Fragrance
            </p>
          </div>
          <div className="flex flex-col ml-5 w-[22%] max-md:ml-0 max-md:w-full">
            <button className="justify-center items-start px-6 mx-auto text-4xl font-bold text-black rounded-full border-teal-900 border-solid bg-stone-500 border-[3px] h-[166px] stroke-[3px] w-[166px] max-md:px-5 max-md:mt-10">
              Shop <br /> Now
            </button>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Hero;