/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const ProductCard = ({ name, price }) => {
  return (
    <div className="flex flex-col w-[31%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow text-3xl font-bold max-md:mt-10">
        <div className="flex flex-col py-3 text-black rounded-xl border-teal-900 border-solid border-[3px]">
          <div className="text-2xl">Best Sellers</div>
          <div className="mt-6">{name}</div>
          <div className="mt-7">#{price}</div>
        </div>
        <button className="justify-center px-5 py-7 mt-7 text-white rounded-md bg-stone-700">
          Add to cart
        </button>
      </div>
    </div>
  );
};

export default ProductCard;