/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const ReviewCard = ({ name, location, review }) => {
  return (
    <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow pt-16 pb-5 w-full text-4xl text-white bg-green-300 rounded-xl shadow-sm max-md:mt-10 max-md:max-w-full">
        <div className="flex flex-col pr-14 pl-2.5 font-bold max-md:pr-5 max-md:max-w-full">
          <h3 className="text-6xl max-md:max-w-full max-md:text-4xl">{name}</h3>
          <p className="mt-12 max-md:mt-10 max-md:max-w-full">{location}</p>
          <blockquote className="items-start px-2.5 pt-6 pb-4 mt-16 rounded-xl border border-solid border-neutral-400 max-md:pr-5 max-md:mt-10 max-md:max-w-full">
            {review}
          </blockquote>
        </div>
        <button className="self-end mt-16 mr-14 max-md:mt-10 max-md:mr-2.5">Read more....</button>
      </div>
    </div>
  );
};

export default ReviewCard;