/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import MainLayout from '../components/MainLayout';

const HomePage = () => {
  return (
    <MainLayout />
  );
};

export default HomePage;