/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function Footer() {
  const navItems = [
    { label: 'Home', icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/caf67bc5de1d3b1cfeb0e0da4e80f8ccc0272c1be50eecc7c52544061961f632?apiKey=661e1fa212c74d1c94d19e320025bbf6&', active: true },
    { label: 'My bookings', icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/6d88749d2b14fa8c865da72f239b3fc8e51e0c3634189580faa13df1123fd0f0?apiKey=661e1fa212c74d1c94d19e320025bbf6&', active: false },
    { label: 'Support', icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/248150b7f27672702c5a5ed9a355967d24e06e38d0914a16ef303780faf14434?apiKey=661e1fa212c74d1c94d19e320025bbf6&', active: false },
    { label: 'My Profile', icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/a7f4bf495acf29d522b2b317264ce507ac10c7a3f8c80ce13622134a17a56d73?apiKey=661e1fa212c74d1c94d19e320025bbf6&', active: false },
  ];

  return (
    <footer className="self-stretch px-9 py-5 mt-12 w-full bg-sky-600">
      <nav className="flex gap-5 max-md:flex-col max-md:gap-0">
        {navItems.map((item, index) => (
          <div key={index} className={`flex flex-col ${index === 0 ? 'w-[17%]' : index === 1 ? 'w-[33%]' : index === 2 ? 'w-[22%]' : 'w-[28%]'} max-md:ml-0 max-md:w-full`}>
            <button className={`flex flex-col grow text-sm ${item.active ? 'font-bold text-slate-900' : 'text-white'} ${item.label === 'My bookings' ? '' : 'font-bold'} ${item.label === 'Support' || item.label === 'My Profile' ? 'whitespace-nowrap' : ''}`}>
              <img loading="lazy" src={item.icon} alt="" className={`self-center ${item.label === 'Support' ? 'aspect-[1.14] w-[51px]' : 'w-10 aspect-square'} ${item.active ? 'fill-slate-900' : 'fill-white'}`} />
              <span className={item.label === 'Support' ? 'mt-1.5' : 'mt-2.5'}>{item.label}</span>
            </button>
          </div>
        ))}
      </nav>
    </footer>
  );
}

export default Footer;