/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import SearchBar from './SearchBar';
import NavigationTabs from './NavigationTabs';

function Header() {
  return (
    <header className="flex flex-col self-stretch px-5 pt-14 pb-6 w-full bg-sky-600 rounded-none">
      <SearchBar />
      <NavigationTabs />
    </header>
  );
}

export default Header;