/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function NavigationTabs() {
  const tabs = [
    { label: 'Hotel', active: false },
    { label: 'Flights', active: true },
    { label: 'Tours', active: false },
  ];

  return (
    <nav className="flex gap-4 items-start mt-16">
      <div className="flex flex-auto gap-4 items-start text-xl text-white whitespace-nowrap">
        {tabs.map((tab, index) => (
          <button
            key={index}
            className={`justify-center items-start px-5 py-5 rounded-3xl ${
              tab.active ? 'bg-zinc-200 bg-opacity-30 border border-white border-solid' : 'bg-sky-600'
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>
      <div className="flex gap-2 items-start mt-2">
        <span className="shrink-0 w-0.5 border border-solid aspect-[0.05] border-black border-opacity-50 stroke-[1px] stroke-black stroke-opacity-50"></span>
        <button className="flex justify-center items-center">
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/eb9e020e943a65e05870d9b5f0415d41c41f1bb5315d279e12a87f0c85b28914?apiKey=661e1fa212c74d1c94d19e320025bbf6&" alt="Menu" className="aspect-[0.54] fill-black fill-opacity-60 w-[25px]" />
        </button>
      </div>
    </nav>
  );
}

export default NavigationTabs;