/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function SearchBar() {
  return (
    <div className="flex gap-5 self-center py-1 text-xl font-light whitespace-nowrap bg-white rounded-3xl text-black text-opacity-60 w-[375px] max-sm:w-[290px]">
      <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/d6e41ac9c892e9497f1a09ce09772fe09d1fdcfc59685de27d0ae3cba5547f22?apiKey=661e1fa212c74d1c94d19e320025bbf6&" alt="" className="shrink-0 bg-blue-600 rounded-full border border-black border-solid aspect-[0.94] stroke-[1px] w-[50px]" />
      <label htmlFor="searchInput" className="sr-only">Search</label>
      <input id="searchInput" type="text" placeholder="Search" className="flex-auto my-auto bg-transparent border-none outline-none" />
    </div>
  );
}

export default SearchBar;