/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function SearchOptions() {
  return (
    <section className="mt-9 w-full max-w-[390px]">
      <div className="flex gap-1 text-black text-opacity-30">
        <button className="flex gap-5 items-start px-7 pt-7 pb-3 text-2xl bg-zinc-300 bg-opacity-40 rounded-[51px]">
          <span className="flex-auto">Round-trip</span>
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/ee24863fda4d4acfeb8fd94f83255bf3e7f33a142ea8f148da8d0e562485b80d?apiKey=661e1fa212c74d1c94d19e320025bbf6&" alt="" className="shrink-0 mt-1 w-6 aspect-square" />
        </button>
        <button className="flex gap-3 items-start pt-8 pr-4 pb-4 pl-2 text-xl bg-zinc-300 bg-opacity-40 rounded-[51px]">
          <span className="grow">1 passenger</span>
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/9a08b65c98d34593681a13dda9e5767b6f70954bf3d289fdbda516291c946250?apiKey=661e1fa212c74d1c94d19e320025bbf6&" alt="" className="shrink-0 aspect-[1.69] fill-black w-[17px]" />
        </button>
      </div>
    </section>
  );
}

export default SearchOptions;