/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import CircleIcon from './CircleIcon';
import IconButton from './IconButton';

const BookingComponent = () => {
  const iconButtons = [
    { src: "https://cdn.builder.io/api/v1/image/assets/TEMP/209da785fbc27cf212a232c4d67f037a4ddb0b9da3f36c3e85b817e985cc331d?apiKey=661e1fa212c74d1c94d19e320025bbf6&", alt: "Service icon", className: "shrink-0 self-start aspect-[1.69] fill-white w-[17px]" },
    { src: "https://cdn.builder.io/api/v1/image/assets/TEMP/00c81104f94b5a527e40ca9d89c799a275ab7c231b4eb78170648e159c3b3767?apiKey=661e1fa212c74d1c94d19e320025bbf6&", alt: "Additional info icon", className: "shrink-0 w-4 aspect-[1.33] fill-white" },
    { src: "https://cdn.builder.io/api/v1/image/assets/TEMP/4e49f0f7f1a2176a376d41d3bdacb74233d968e389a34000be6e0d98611f8632?apiKey=661e1fa212c74d1c94d19e320025bbf6&", alt: "Menu icon", className: "shrink-0 w-8 aspect-[3.57] fill-white" },
    { src: "https://cdn.builder.io/api/v1/image/assets/TEMP/d8b7d8110dd05c2711e449786af01a683e4bcf01151005fc3ba70921cf066574?apiKey=661e1fa212c74d1c94d19e320025bbf6&", alt: "User profile icon", className: "shrink-0 aspect-[2.44] w-[27px]" },
  ];

  return (
    <main className="flex flex-col mx-auto w-full max-w-[480px] overflow-hidden">
      <header className="w-full">
        <div className="flex gap-5 max-md:flex-col max-md:gap-0">
          <div className="flex flex-col w-[23%] max-md:ml-0 max-md:w-full">
            <CircleIcon className="mx-auto h-[101px] w-[119px]" />
          </div>
          <nav className="flex flex-col ml-5 w-[77%] max-md:ml-0 max-md:w-full">
            <div className="flex gap-5 justify-between items-start pr-3 mt-4 w-full text-xs font-medium tracking-normal leading-3 text-white whitespace-nowrap">
              <div className="flex gap-1 self-stretch pr-4">
                {iconButtons.slice(0, 2).map((button, index) => (
                  <IconButton key={index} {...button} />
                ))}
                <div>Service</div>
              </div>
              {iconButtons.slice(2).map((button, index) => (
                <IconButton key={index + 2} {...button} />
              ))}
            </div>
          </nav>
        </div>
      </header>
      <section className="flex z-10 flex-col items-start pl-20 mt-0 w-full">
        <CircleIcon />
        <div className="flex gap-0 mt-8">
          <h1 className="z-10 grow my-auto text-6xl font-extrabold text-blue-900">
            Book{" "}
          </h1>
          <div className="flex flex-col">
            <CircleIcon />
            <CircleIcon className="self-end" />
          </div>
        </div>
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/0c43040bf4a5a4ec836f3f9299ed57cef0531317048d384b8d80548c64088462?apiKey=661e1fa212c74d1c94d19e320025bbf6&" alt="Booking illustration" className="mt-5 max-w-full aspect-[1.09] w-[277px]" />
      </section>
      <section className="flex gap-0 mt-20 w-full">
        <div className="z-10 flex-auto">
          <div className="flex gap-5 max-md:flex-col max-md:gap-0">
            <div className="flex flex-col w-[70%] max-md:ml-0 max-md:w-full">
              <div className="flex flex-col grow mt-2 text-3xl font-extrabold text-white">
                <button className="z-10 justify-center self-end px-12 py-6 bg-sky-600 rounded-3xl">
                  Get Started
                </button>
                <CircleIcon className="h-[119px] w-[108px]" />
              </div>
            </div>
            <div className="flex flex-col ml-5 w-[30%] max-md:ml-0 max-md:w-full">
              <div className="flex flex-col">
                <CircleIcon />
                <div className="flex gap-2.5 self-end">
                  <div className="shrink-0 rounded-full bg-zinc-300 h-[13px] w-[13px]" />
                  <div className="shrink-0 rounded-full bg-blue-950 h-[13px] w-[13px]" />
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="shrink-0 self-start mt-28 rounded-full bg-zinc-300 h-[13px] w-[13px]" />
      </section>
    </main>
  );
};

export default BookingComponent;