/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const CircleIcon = ({ className }) => (
  <div className={`shrink-0 bg-sky-600 rounded-full h-[119px] w-[119px] ${className}`} />
);

export default CircleIcon;