/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const IconButton = ({ src, alt, className }) => (
  <img loading="lazy" src={src} alt={alt} className={className} />
);

export default IconButton;