/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import booking from '../../../../public/imgs/booking.png'
import support from '../../../../public/imgs/support.png'
import profile from '../../../../public/imgs/profile.png'
import Image from 'next/image';
import Link from 'next/link';

function BottomNavigation() {
  return (
    <nav className="flex gap-y-5 gap-x-4 self-start px-10 pt-1.5 pb-3 text-sm bg-sky-600 w-full">
      <div className="flex flex-col self-start mt-5 font-bold whitespace-nowrap text-slate-900">
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/caf67bc5de1d3b1cfeb0e0da4e80f8ccc0272c1be50eecc7c52544061961f632?apiKey=661e1fa212c74d1c94d19e320025bbf6&" alt="" className="self-center w-10 aspect-square fill-slate-900" />
        <div className="mt-3.5">Home</div>
      </div>
      {/* <div className="flex flex-auto gap-1"> */}
        <Link href={'/'} className="flex flex-col self-start items-center mt-5 font-bold text-white">
          <Image loading="lazy" src={booking} alt="" className="aspect-[1] w-[40px]" />
          <div className="mt-3.5 w-[90px]">My bookings</div>
        </Link>
        <Link href={'/'} className="flex flex-col self-start items-center mt-5 font-bold text-white"> 
          <Image loading="lazy" src={support} alt="" className="aspect-[1] w-[40px]" />
          <div className="mt-3.5">Support</div>
        </Link>
        <Link href={'/'} className="flex flex-col self-start items-center mt-5 font-bold text-white">
          <Image loading="lazy" src={profile} alt="" className="aspect-[1] w-[40px]" />
          <div className="mt-3.5 w-[80px]">My Profile</div>
        </Link>
        
      {/* </div> */}
    </nav>
    // <nav className="flex gap-5 self-start px-10 pt-1.5 pb-3 text-sm bg-sky-600">
    //   <div className="flex flex-col self-start mt-5 font-bold whitespace-nowrap text-slate-900">
    //     <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/caf67bc5de1d3b1cfeb0e0da4e80f8ccc0272c1be50eecc7c52544061961f632?apiKey=661e1fa212c74d1c94d19e320025bbf6&" alt="" className="self-center w-10 aspect-square fill-slate-900" />
    //     <div className="mt-3.5">Home</div>
    //   </div>
    //   <div className="flex flex-auto gap-1.5">
    //     <div className="flex flex-col self-start mt-5 font-bold text-white">
    //       <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/d767bc5f179e547e4d3cc0f6725728ce54897e1d362c40be0cfadc59cee98019?apiKey=661e1fa212c74d1c94d19e320025bbf6&" alt="" className="aspect-[1.49] w-[60px]" />
    //       <div className="mt-3.5">My bookings</div>
    //     </div>
    //     <div className="flex flex-col">
    //       <p className="text-black">
    //         It is a visionary beachfront resort that fuses California cool and Dubai spectacle.
    //       </p>
    //       <div className="flex gap-5 justify-between self-end mt-6 font-bold text-white">
    //         <button>Support</button>
    //         <button>My Profile</button>
    //       </div>
    //     </div>
    //   </div>
    // </nav>
  );
}

export default BottomNavigation;