/**
 * This code was generated by Builder.io.
 */
'use client'
import React from 'react';
import SearchBar from './SearchBar';
import CategoryTabs from './CategoryTabs';
import HotelCard from './HotelCard';
import BottomNavigation from './BottomNavigation';
import { useState } from 'react';

const hotelData = [
  {
    name: 'Eko Hotels',
    image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/6a92023b23ed0964c0c9bc69dd4091d43b1529962f3880b8030c84a23e2f22e1?apiKey=661e1fa212c74d1c94d19e320025bbf6&',
    rating: '9.5',
    description: 'An 8-minute walk from Kuramo Beach on the Gulf of Guinea, this relaxed hotel is 6 km from the Nigerian National Museum.',
  },
  {
    name: 'Five Hotel',
    image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/d844dd12bb39ba4bea1fe762731f1891f2fed22ce0faea11960cd632ec822617?apiKey=661e1fa212c74d1c94d19e320025bbf6&',
    rating: '9.5',
    description: 'It is a visionary beachfront resort that fuses California cool and Dubai spectacle.',
  },
  {
    name: 'Maroon Hotel',
    image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/052febea3a1cf889b79d1b784acde12605bce48c5151fe9b809f3ea15ff7e582?apiKey=661e1fa212c74d1c94d19e320025bbf6&',
    rating: '9.5',
    description: 'It is a visionary beachfront resort that fuses California cool and Dubai spectacle.',
  },
];

function HotelBooking() {
  const [hotel, setHotel] = useState('')
  const [searchedHotel, setSearchedHotel] = useState(hotelData)
  return (
    <main className="flex flex-col items-center justify-center mx-auto w-full max-w-[480px] overflow-hidden xs:max-[400px]:max-w-[360px]">
      <header className="flex flex-col self-stretch px-5 pt-5 pb-3.5 w-full bg-sky-600 rounded-none xs:max-[400px]:max-w-[360px]">
        <h1 className="self-start ml-20 text-5xl font-extrabold text-white">
          Book
        </h1>
        <SearchBar hotel={hotel} setHotel={setHotel} searchedHotel={searchedHotel} setSearchedHotel
        ={setSearchedHotel} hotelData={hotelData}/>
        <CategoryTabs />
      </header>
      
      {searchedHotel.map((hotel, index) => (
        <HotelCard key={index} {...hotel} />
      ))}
      
      <HotelCard
        name="Maroon Hotel"
        image="https://cdn.builder.io/api/v1/image/assets/TEMP/052febea3a1cf889b79d1b784acde12605bce48c5151fe9b809f3ea15ff7e582?apiKey=661e1fa212c74d1c94d19e320025bbf6&"
        rating="9.5"
        description="It is a visionary beachfront resort that fuses California cool and Dubai spectacle."
        // showBottomNav
      />
      <div className='w-full sm:max-2xl:mx-auto'>
        <BottomNavigation/>
      </div>
    </main>
  );
}

export default HotelBooking;