/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import BottomNavigation from './BottomNavigation';

function HotelCard({ name, image, rating, description, showBottomNav }) {
  return (
    <article className="flex gap-2 mt-7 w-full text-black bg-white shadow-sm overflow-hidden xs:max-[400px]:max-w-[360px] pr-4">
      <img loading="lazy" src={image} alt={name} className="shrink-0 w-40 max-w-full border border-sky-600 border-solid shadow-sm aspect-[1.02]" />
      <div className="flex flex-col self-start mt-2.5">
        <div className="flex gap-5 justify-between">
          <h2 className="grow text-2xl font-bold">{name}</h2>
          <div className="flex gap-1.5 self-start items-center justify-center text-sm whitespace-nowrap">
            <div className="my-auto">{rating}</div>
            <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/c25ba3949fc46757f2a3e4e76b50606608fc7b269e0cee0d2fc333cc805db4a5?apiKey=661e1fa212c74d1c94d19e320025bbf6&" alt="Star rating" className="shrink-0 w-6 aspect-square fill-amber-200" />
          </div>
        </div>
        <p className="mt-3 text-sm">{description}</p>
        <button className="self-end mt-5 text-xs text-sky-600">Show More</button>
      </div>
      <div className='block'>
      {/* {showBottomNav && <BottomNavigation />} */}
      </div>
      
    </article>
  );
}

export default HotelCard;