/**
 * This code was generated by Builder.io.
 */
'use client'
import React from 'react';
import { useState } from 'react';

function SearchBar({hotel, setHotel, searchedHotel, setSearchedHotel, hotelData}) {
  

  const handleChange = (e) => {
    setHotel(e.target.value)
    const filteredHotel = hotelData.filter(h=> {return h.name.toLowerCase().includes(e.target.value.toLowerCase())})
    if (filteredHotel && filteredHotel.length>0) {
      setSearchedHotel(filteredHotel)
    } else {
      setSearchedHotel(hotelData)
    }
       

  }
  return (
    <form className="flex gap-4 self-center px-2.5 py-1 mt-20 text-xl font-light whitespace-nowrap bg-white rounded-3xl text-black text-opacity-60">
      <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/d0cd7cdae247a451d066d7971ada27689cb612413d38e5256a2a5a26699fae54?apiKey=661e1fa212c74d1c94d19e320025bbf6&" alt="" className="shrink-0 aspect-square w-[50px]" />
      <label htmlFor="searchInput" className="sr-only">Search</label>
      <input
        type="text"
        id="searchInput"
        placeholder="Search"
        className="flex-auto my-auto bg-transparent border-none focus:outline-none"
        name='hotel'
        value={hotel}
        onChange={handleChange}
      />
    </form>
  );
}

export default SearchBar;